/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package appcrud;

import java.awt.Color;
import java.awt.Component;
import javax.swing.JButton;

/**
 *
 * @author harol
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public VentanaPrincipal() {
        initComponents();
        getContentPane().setBackground(new Color(250, 250, 250)); // Gris claro elegante
        // Aplicar color a todos los botones automáticamente
        setButtonColors(new Color(0, 111, 201), Color.WHITE); // Fondo azul moderno, texto blanco
        setLocationRelativeTo(null); // Centra la ventana en la pantalla

    }
    
    private void setButtonColors(Color background, Color foreground) {
        for (Component c : getContentPane().getComponents()) {
            if (c instanceof JButton) {
                c.setBackground(background);
                c.setForeground(foreground);
                ((JButton) c).setFocusPainted(false); // Elimina el borde azul al hacer clic
                ((JButton) c).setBorderPainted(false); // Quita los bordes del botón
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombre = new javax.swing.JLabel();
        numero = new javax.swing.JLabel();
        campoNombre = new javax.swing.JTextField();
        campoNumero = new javax.swing.JTextField();
        create = new javax.swing.JButton();
        read = new javax.swing.JButton();
        update = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        clean = new javax.swing.JButton();
        agenda = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Agenda");

        nombre.setText("Nombre");

        numero.setText("Número");

        campoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNombreActionPerformed(evt);
            }
        });

        create.setText("Crear");
        create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createActionPerformed(evt);
            }
        });

        read.setText("Leer");
        read.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readActionPerformed(evt);
            }
        });

        update.setText("Actualizar");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        delete.setText("Eliminar");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        clean.setText("Limpiar");
        clean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cleanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(numero)
                        .addGap(18, 18, 18)
                        .addComponent(campoNumero))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nombre)
                        .addGap(18, 18, 18)
                        .addComponent(campoNombre))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(create)
                        .addGap(12, 12, 12)
                        .addComponent(read)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(update)
                        .addGap(18, 18, 18)
                        .addComponent(delete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(clean))
                    .addComponent(agenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombre)
                    .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numero)
                    .addComponent(campoNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(create)
                    .addComponent(update)
                    .addComponent(delete)
                    .addComponent(clean)
                    .addComponent(read))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(agenda, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createActionPerformed
        // Obtener valores de los campos
            String nombre = campoNombre.getText();
            String numeroStr = campoNumero.getText();

            try {
                // Convertir el número a long
                long numero = Long.parseLong(numeroStr);

                // Llamar a la clase AddFriend
                String resultado = AddFriend.addFriend(nombre, numero);

                // Mostrar el resultado en el JLabel
                agenda.setText(resultado);
            } catch (NumberFormatException ex) {
                agenda.setText("Número inválido. Introduce un número válido.");
            }
    }//GEN-LAST:event_createActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
    // Obtener valores de los campos
    String nombre = campoNombre.getText();
    String numeroStr = campoNumero.getText();

    try {
        // Convertir el número a long
        long numero = Long.parseLong(numeroStr);

        // Llamar a la clase UpdateFriend
        UpdateFriend.updateFriend(nombre, numero); 

        // Mostrar el resultado en el JLabel
        agenda.setText("El contacto ha sido actualizado");
    } catch (NumberFormatException ex) {
        agenda.setText("Número inválido. Introduce un número válido.");
    }
    }//GEN-LAST:event_updateActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // Obtener valores de los campos
            String nombre = campoNombre.getText();
            String numeroStr = campoNumero.getText();

            try {
                // Convertir el número a long
                long numero = Long.parseLong(numeroStr);

                // Llamar a la clase AddFriend
                String resultado = DeleteFriend.deleteFriend(nombre, numero);

                // Mostrar el resultado en el JLabel
                agenda.setText(resultado);
            } catch (NumberFormatException ex) {
                agenda.setText("Número inválido. Introduce un número válido.");
            }
    }//GEN-LAST:event_deleteActionPerformed

    private void cleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cleanActionPerformed
         // Limpiar los campos de texto
        campoNombre.setText(""); // Limpia el campoNombre
        campoNumero.setText(""); // Limpia el campoNumero
        agenda.setText("");

    }//GEN-LAST:event_cleanActionPerformed

    private void campoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNombreActionPerformed

    private void readActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readActionPerformed
        // Llamar a la clase DisplayFriends para obtener los contactos
    String resultado = DisplayFriends.getContacts();
    
    // Mostrar el resultado en el JLabel
    agenda.setText("<html>" + resultado.replace("\n", "<br>") + "</html>"); 
    pack(); // Ajusta el tamaño de la ventana
    }//GEN-LAST:event_readActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel agenda;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JTextField campoNumero;
    private javax.swing.JButton clean;
    private javax.swing.JButton create;
    private javax.swing.JButton delete;
    private javax.swing.JLabel nombre;
    private javax.swing.JLabel numero;
    private javax.swing.JButton read;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
